---@class ItemUpgradeTipMythicPlusRowMixin: ItemUpgradeTipResultsRowTemplateMixin
ItemUpgradeTipMythicPlusRowMixin = CreateFromMixins(ItemUpgradeTipResultsRowTemplateMixin)

ItemUpgradeTipMythicPlusRowMixin.Populate = ItemUpgradeTipTableResultsRowMixin.Populate
ItemUpgradeTipMythicPlusRowMixin.OnClick = ItemUpgradeTipTableResultsRowMixin.OnClick

function ItemUpgradeTipMythicPlusRowMixin:OnHide()
end
