---@class ItemUpgradeTipBountifulDelvesRowMixin: ItemUpgradeTipResultsRowTemplateMixin
ItemUpgradeTipBountifulDelvesRowMixin = CreateFromMixins(ItemUpgradeTipResultsRowTemplateMixin)

ItemUpgradeTipBountifulDelvesRowMixin.Populate = ItemUpgradeTipTableResultsRowMixin.Populate
ItemUpgradeTipBountifulDelvesRowMixin.OnClick = ItemUpgradeTipTableResultsRowMixin.OnClick

function ItemUpgradeTipBountifulDelvesRowMixin:OnHide()
end
