---@class ItemUpgradeTipUpgradeRowMixin: ItemUpgradeTipResultsRowTemplateMixin
ItemUpgradeTipUpgradeRowMixin = CreateFromMixins(ItemUpgradeTipResultsRowTemplateMixin)

ItemUpgradeTipUpgradeRowMixin.Populate = ItemUpgradeTipTableResultsRowMixin.Populate
ItemUpgradeTipUpgradeRowMixin.OnClick = ItemUpgradeTipTableResultsRowMixin.OnClick

function ItemUpgradeTipUpgradeRowMixin:OnHide()
end
